run:
  timeout: 10m
linters:
  enable-all: true
  disable:
    - cyclop
    - wsl
    - godox
    - gochecknoglobals
    - ireturn
    - nlreturn
    - testpackage
    - paralleltest
    - exhaustivestruct
    - exhaustruct
    - gocognit
    - gochecknoinits
    - gocyclo
