version: "2"
linters:
  default: all
  disable:
    - cyclop
    - exhaustruct
    - gochecknoglobals
    - gochecknoinits
    - gocognit
    - gocyclo
    - godox
    - ireturn
    - nlreturn
    - paralleltest
    - testpackage
    - wsl
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
